---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - s3.sedex.io
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.sedex.io
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - s3.sedex.io
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
